# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sweep_generate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sweep_window(object):
    def setupUi(self, sweep_window):
        sweep_window.setObjectName("sweep_window")
        sweep_window.resize(260, 234)
        self.verticalLayout = QtWidgets.QVBoxLayout(sweep_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(sweep_window)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.Layout_startfreq = QtWidgets.QHBoxLayout()
        self.Layout_startfreq.setObjectName("Layout_startfreq")
        self.label_startfreq = QtWidgets.QLabel(sweep_window)
        self.label_startfreq.setAlignment(QtCore.Qt.AlignCenter)
        self.label_startfreq.setObjectName("label_startfreq")
        self.Layout_startfreq.addWidget(self.label_startfreq)
        self.startfreq = QtWidgets.QSpinBox(sweep_window)
        self.startfreq.setMaximum(40000)
        self.startfreq.setObjectName("startfreq")
        self.Layout_startfreq.addWidget(self.startfreq)
        self.verticalLayout.addLayout(self.Layout_startfreq)
        self.Layout_endfreq = QtWidgets.QHBoxLayout()
        self.Layout_endfreq.setObjectName("Layout_endfreq")
        self.label_endfreq = QtWidgets.QLabel(sweep_window)
        self.label_endfreq.setAlignment(QtCore.Qt.AlignCenter)
        self.label_endfreq.setObjectName("label_endfreq")
        self.Layout_endfreq.addWidget(self.label_endfreq)
        self.endfreq = QtWidgets.QSpinBox(sweep_window)
        self.endfreq.setMaximum(40000)
        self.endfreq.setObjectName("endfreq")
        self.Layout_endfreq.addWidget(self.endfreq)
        self.verticalLayout.addLayout(self.Layout_endfreq)
        self.Layout_duration = QtWidgets.QHBoxLayout()
        self.Layout_duration.setObjectName("Layout_duration")
        self.label_duration = QtWidgets.QLabel(sweep_window)
        self.label_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.label_duration.setObjectName("label_duration")
        self.Layout_duration.addWidget(self.label_duration)
        self.duration = QtWidgets.QDoubleSpinBox(sweep_window)
        self.duration.setMaximum(999.99)
        self.duration.setSingleStep(0.001)
        self.duration.setObjectName("duration")
        self.Layout_duration.addWidget(self.duration)
        self.verticalLayout.addLayout(self.Layout_duration)
        self.Layout_samplerate = QtWidgets.QHBoxLayout()
        self.Layout_samplerate.setObjectName("Layout_samplerate")
        self.label_samplerate = QtWidgets.QLabel(sweep_window)
        self.label_samplerate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_samplerate.setObjectName("label_samplerate")
        self.Layout_samplerate.addWidget(self.label_samplerate)
        self.samplerate = QtWidgets.QSpinBox(sweep_window)
        self.samplerate.setMaximum(99999)
        self.samplerate.setObjectName("samplerate")
        self.Layout_samplerate.addWidget(self.samplerate)
        self.verticalLayout.addLayout(self.Layout_samplerate)
        self.Layout_type = QtWidgets.QHBoxLayout()
        self.Layout_type.setObjectName("Layout_type")
        self.label_type = QtWidgets.QLabel(sweep_window)
        self.label_type.setAlignment(QtCore.Qt.AlignCenter)
        self.label_type.setObjectName("label_type")
        self.Layout_type.addWidget(self.label_type)
        self.type = QtWidgets.QComboBox(sweep_window)
        self.type.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.type.setObjectName("type")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.Layout_type.addWidget(self.type)
        self.verticalLayout.addLayout(self.Layout_type)
        self.buttonBox = QtWidgets.QDialogButtonBox(sweep_window)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(sweep_window)
        self.buttonBox.accepted.connect(sweep_window.accept) # type: ignore
        self.buttonBox.rejected.connect(sweep_window.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(sweep_window)

    def retranslateUi(self, sweep_window):
        _translate = QtCore.QCoreApplication.translate
        sweep_window.setWindowTitle(_translate("sweep_window", "扫频信号生成"))
        self.label_1.setText(_translate("sweep_window", "参数设置"))
        self.label_startfreq.setText(_translate("sweep_window", "起始频率："))
        self.label_endfreq.setText(_translate("sweep_window", "终止频率："))
        self.label_duration.setText(_translate("sweep_window", "扫描时间（s）："))
        self.label_samplerate.setText(_translate("sweep_window", "采样率(hz)："))
        self.label_type.setText(_translate("sweep_window", "扫频类型："))
        self.type.setItemText(0, _translate("sweep_window", "线性"))
        self.type.setItemText(1, _translate("sweep_window", "对数"))
        self.type.setItemText(2, _translate("sweep_window", "双曲线"))
        self.type.setItemText(3, _translate("sweep_window", "抛物线"))
