# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\square_generate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SquareSignal(object):
    def setupUi(self, SquareSignal):
        SquareSignal.setObjectName("SquareSignal")
        SquareSignal.resize(176, 199)
        self.verticalLayout = QtWidgets.QVBoxLayout(SquareSignal)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SquareSignal)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Layout_freq = QtWidgets.QHBoxLayout()
        self.Layout_freq.setObjectName("Layout_freq")
        self.label_freq = QtWidgets.QLabel(SquareSignal)
        self.label_freq.setAlignment(QtCore.Qt.AlignCenter)
        self.label_freq.setObjectName("label_freq")
        self.Layout_freq.addWidget(self.label_freq)
        self.freq = QtWidgets.QSpinBox(SquareSignal)
        self.freq.setMaximum(40000)
        self.freq.setObjectName("freq")
        self.Layout_freq.addWidget(self.freq)
        self.verticalLayout.addLayout(self.Layout_freq)
        self.Layout_ratio = QtWidgets.QHBoxLayout()
        self.Layout_ratio.setObjectName("Layout_ratio")
        self.label_ratio = QtWidgets.QLabel(SquareSignal)
        self.label_ratio.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ratio.setObjectName("label_ratio")
        self.Layout_ratio.addWidget(self.label_ratio)
        self.ratio = QtWidgets.QSpinBox(SquareSignal)
        self.ratio.setMaximum(100)
        self.ratio.setObjectName("ratio")
        self.Layout_ratio.addWidget(self.ratio)
        self.verticalLayout.addLayout(self.Layout_ratio)
        self.Layout_duration = QtWidgets.QHBoxLayout()
        self.Layout_duration.setObjectName("Layout_duration")
        self.label_duration = QtWidgets.QLabel(SquareSignal)
        self.label_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.label_duration.setObjectName("label_duration")
        self.Layout_duration.addWidget(self.label_duration)
        self.duration = QtWidgets.QDoubleSpinBox(SquareSignal)
        self.duration.setDecimals(2)
        self.duration.setMaximum(999.99)
        self.duration.setSingleStep(0.01)
        self.duration.setObjectName("duration")
        self.Layout_duration.addWidget(self.duration)
        self.verticalLayout.addLayout(self.Layout_duration)
        self.Layout_samplerate = QtWidgets.QHBoxLayout()
        self.Layout_samplerate.setObjectName("Layout_samplerate")
        self.label_samplerate = QtWidgets.QLabel(SquareSignal)
        self.label_samplerate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_samplerate.setObjectName("label_samplerate")
        self.Layout_samplerate.addWidget(self.label_samplerate)
        self.samplerate = QtWidgets.QSpinBox(SquareSignal)
        self.samplerate.setMinimum(1)
        self.samplerate.setMaximum(99999)
        self.samplerate.setObjectName("samplerate")
        self.Layout_samplerate.addWidget(self.samplerate)
        self.verticalLayout.addLayout(self.Layout_samplerate)
        self.buttonBox = QtWidgets.QDialogButtonBox(SquareSignal)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 2)
        self.verticalLayout.setStretch(4, 2)
        self.verticalLayout.setStretch(5, 2)

        self.retranslateUi(SquareSignal)
        self.buttonBox.accepted.connect(SquareSignal.accept) # type: ignore
        self.buttonBox.rejected.connect(SquareSignal.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SquareSignal)

    def retranslateUi(self, SquareSignal):
        _translate = QtCore.QCoreApplication.translate
        SquareSignal.setWindowTitle(_translate("SquareSignal", "矩形信号生成"))
        self.label.setText(_translate("SquareSignal", "请设置您的参数"))
        self.label_freq.setText(_translate("SquareSignal", "频率（hz）："))
        self.label_ratio.setText(_translate("SquareSignal", "占空比（%）："))
        self.label_duration.setText(_translate("SquareSignal", "持续时间（s）："))
        self.label_samplerate.setText(_translate("SquareSignal", "采样率（hz）："))
